# -*- coding: utf-8 -*-
"""audio_to_spectrograms.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-hMGXXerz9QHw-q0uKxXIUE-M9y_SEas
"""

!unzip -qq /content/drive/MyDrive/Data/covid_cough_database.zip

import pandas as pd
import librosa 
import matplotlib.pyplot as plt
from tqdm import tqdm

filenames = pd.read_csv('/content/cough_trial_extended.csv')

cmap = plt.get_cmap('inferno')

for i in tqdm(range(len(filenames))):
    source = filenames['file_properties'][i]
    filename = '/content/trial_covid/'+source
    y, sr = librosa.load(filename, mono=True, duration=5)
    plt.specgram(y, NFFT=2048, Fs=2, Fc=0, noverlap=128, cmap=cmap, sides='default', mode='default', scale='dB')
    plt.axis('off')
    plt.savefig(f'Extracted/{source[:-3].replace(".", "")}.png')
    plt.clf()